//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManage.SmsFactoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsPackage", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities")]
    [System.SerializableAttribute()]
    public partial class SmsPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternativeEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManage.SmsFactoryService.CustomerCredentials CredentialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultMessageTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClientManage.SmsFactoryService.SmsMessage> MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotifyUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManage.SmsFactoryService.SmsPackagePaging PagingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternativeEmail {
            get {
                return this.AlternativeEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternativeEmailField, value) != true)) {
                    this.AlternativeEmailField = value;
                    this.RaisePropertyChanged("AlternativeEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManage.SmsFactoryService.CustomerCredentials Credentials {
            get {
                return this.CredentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialsField, value) != true)) {
                    this.CredentialsField = value;
                    this.RaisePropertyChanged("Credentials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultMessageText {
            get {
                return this.DefaultMessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultMessageTextField, value) != true)) {
                    this.DefaultMessageTextField = value;
                    this.RaisePropertyChanged("DefaultMessageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpireDate {
            get {
                return this.ExpireDateField;
            }
            set {
                if ((this.ExpireDateField.Equals(value) != true)) {
                    this.ExpireDateField = value;
                    this.RaisePropertyChanged("ExpireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDemo {
            get {
                return this.IsDemoField;
            }
            set {
                if ((this.IsDemoField.Equals(value) != true)) {
                    this.IsDemoField = value;
                    this.RaisePropertyChanged("IsDemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClientManage.SmsFactoryService.SmsMessage> Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotifyUrl {
            get {
                return this.NotifyUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.NotifyUrlField, value) != true)) {
                    this.NotifyUrlField = value;
                    this.RaisePropertyChanged("NotifyUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManage.SmsFactoryService.SmsPackagePaging Paging {
            get {
                return this.PagingField;
            }
            set {
                if ((object.ReferenceEquals(this.PagingField, value) != true)) {
                    this.PagingField = value;
                    this.RaisePropertyChanged("Paging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIdField, value) != true)) {
                    this.ReferenceIdField = value;
                    this.RaisePropertyChanged("ReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerCredentials", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities")]
    [System.SerializableAttribute()]
    public partial class CustomerCredentials : ClientManage.SmsFactoryService.BaseCredentials {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplicationIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsPackagePaging", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities")]
    [System.SerializableAttribute()]
    public partial class SmsPackagePaging : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> DelayBetweenPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> EndTimeOfDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> StartTimeOfDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> DelayBetweenPages {
            get {
                return this.DelayBetweenPagesField;
            }
            set {
                if ((this.DelayBetweenPagesField.Equals(value) != true)) {
                    this.DelayBetweenPagesField = value;
                    this.RaisePropertyChanged("DelayBetweenPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> EndTimeOfDay {
            get {
                return this.EndTimeOfDayField;
            }
            set {
                if ((this.EndTimeOfDayField.Equals(value) != true)) {
                    this.EndTimeOfDayField = value;
                    this.RaisePropertyChanged("EndTimeOfDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> StartTimeOfDay {
            get {
                return this.StartTimeOfDayField;
            }
            set {
                if ((this.StartTimeOfDayField.Equals(value) != true)) {
                    this.StartTimeOfDayField = value;
                    this.RaisePropertyChanged("StartTimeOfDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsMessage", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities")]
    [System.SerializableAttribute()]
    public partial class SmsMessage : ClientManage.SmsFactoryService.BaseSmsMessage {
        
        private string ToPhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ToPhone {
            get {
                return this.ToPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPhoneField, value) != true)) {
                    this.ToPhoneField = value;
                    this.RaisePropertyChanged("ToPhone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCredentials", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.CustomerCredentials))]
    public partial class BaseCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIdField, value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseSmsMessage", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.BulkSmsMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.SmsMessage))]
    public partial class BaseSmsMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternativeEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EntityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromNameField;
        
        private string FromPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternativeEmail {
            get {
                return this.AlternativeEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternativeEmailField, value) != true)) {
                    this.AlternativeEmailField = value;
                    this.RaisePropertyChanged("AlternativeEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EntityType {
            get {
                return this.EntityTypeField;
            }
            set {
                if ((this.EntityTypeField.Equals(value) != true)) {
                    this.EntityTypeField = value;
                    this.RaisePropertyChanged("EntityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromName {
            get {
                return this.FromNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromNameField, value) != true)) {
                    this.FromNameField = value;
                    this.RaisePropertyChanged("FromName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FromPhone {
            get {
                return this.FromPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.FromPhoneField, value) != true)) {
                    this.FromPhoneField = value;
                    this.RaisePropertyChanged("FromPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText {
            get {
                return this.MessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTextField, value) != true)) {
                    this.MessageTextField = value;
                    this.RaisePropertyChanged("MessageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIdField, value) != true)) {
                    this.ReferenceIdField = value;
                    this.RaisePropertyChanged("ReferenceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkSmsMessage", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities")]
    [System.SerializableAttribute()]
    public partial class BulkSmsMessage : ClientManage.SmsFactoryService.BaseSmsMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ToPhonesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ToPhones {
            get {
                return this.ToPhonesField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPhonesField, value) != true)) {
                    this.ToPhonesField = value;
                    this.RaisePropertyChanged("ToPhones");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFilter", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Filters")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.BaseFilterOfHistoryMessageFdYOpOQC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.BaseHistoryMessageFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.TotalMessagesPerDayFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.HistoryMessageFilter))]
    public partial class BaseFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TakeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Take {
            get {
                return this.TakeField;
            }
            set {
                if ((this.TakeField.Equals(value) != true)) {
                    this.TakeField = value;
                    this.RaisePropertyChanged("Take");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFilterOfHistoryMessageFdYOpOQC", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Filters")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.BaseHistoryMessageFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.TotalMessagesPerDayFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.HistoryMessageFilter))]
    public partial class BaseFilterOfHistoryMessageFdYOpOQC : ClientManage.SmsFactoryService.BaseFilter {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseHistoryMessageFilter", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Filters")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.TotalMessagesPerDayFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.HistoryMessageFilter))]
    public partial class BaseHistoryMessageFilter : ClientManage.SmsFactoryService.BaseFilterOfHistoryMessageFdYOpOQC {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerUniqueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerUniqueId {
            get {
                return this.CustomerUniqueIdField;
            }
            set {
                if ((this.CustomerUniqueIdField.Equals(value) != true)) {
                    this.CustomerUniqueIdField = value;
                    this.RaisePropertyChanged("CustomerUniqueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalMessagesPerDayFilter", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Filters")]
    [System.SerializableAttribute()]
    public partial class TotalMessagesPerDayFilter : ClientManage.SmsFactoryService.BaseHistoryMessageFilter {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSendFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSendToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreatedFrom {
            get {
                return this.DateCreatedFromField;
            }
            set {
                if ((this.DateCreatedFromField.Equals(value) != true)) {
                    this.DateCreatedFromField = value;
                    this.RaisePropertyChanged("DateCreatedFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreatedTo {
            get {
                return this.DateCreatedToField;
            }
            set {
                if ((this.DateCreatedToField.Equals(value) != true)) {
                    this.DateCreatedToField = value;
                    this.RaisePropertyChanged("DateCreatedTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSendFrom {
            get {
                return this.DateSendFromField;
            }
            set {
                if ((this.DateSendFromField.Equals(value) != true)) {
                    this.DateSendFromField = value;
                    this.RaisePropertyChanged("DateSendFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSendTo {
            get {
                return this.DateSendToField;
            }
            set {
                if ((this.DateSendToField.Equals(value) != true)) {
                    this.DateSendToField = value;
                    this.RaisePropertyChanged("DateSendTo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryMessageFilter", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Filters")]
    [System.SerializableAttribute()]
    public partial class HistoryMessageFilter : ClientManage.SmsFactoryService.BaseHistoryMessageFilter {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSendFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSendToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EntityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NotSuccessStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientManage.SmsFactoryService.HistoryMessageFilter.OrderByOptions OrderByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreatedFrom {
            get {
                return this.DateCreatedFromField;
            }
            set {
                if ((this.DateCreatedFromField.Equals(value) != true)) {
                    this.DateCreatedFromField = value;
                    this.RaisePropertyChanged("DateCreatedFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreatedTo {
            get {
                return this.DateCreatedToField;
            }
            set {
                if ((this.DateCreatedToField.Equals(value) != true)) {
                    this.DateCreatedToField = value;
                    this.RaisePropertyChanged("DateCreatedTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSendFrom {
            get {
                return this.DateSendFromField;
            }
            set {
                if ((this.DateSendFromField.Equals(value) != true)) {
                    this.DateSendFromField = value;
                    this.RaisePropertyChanged("DateSendFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSendTo {
            get {
                return this.DateSendToField;
            }
            set {
                if ((this.DateSendToField.Equals(value) != true)) {
                    this.DateSendToField = value;
                    this.RaisePropertyChanged("DateSendTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EntityType {
            get {
                return this.EntityTypeField;
            }
            set {
                if ((this.EntityTypeField.Equals(value) != true)) {
                    this.EntityTypeField = value;
                    this.RaisePropertyChanged("EntityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromName {
            get {
                return this.FromNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromNameField, value) != true)) {
                    this.FromNameField = value;
                    this.RaisePropertyChanged("FromName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromPhone {
            get {
                return this.FromPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.FromPhoneField, value) != true)) {
                    this.FromPhoneField = value;
                    this.RaisePropertyChanged("FromPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText {
            get {
                return this.MessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTextField, value) != true)) {
                    this.MessageTextField = value;
                    this.RaisePropertyChanged("MessageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotSuccessStatus {
            get {
                return this.NotSuccessStatusField;
            }
            set {
                if ((this.NotSuccessStatusField.Equals(value) != true)) {
                    this.NotSuccessStatusField = value;
                    this.RaisePropertyChanged("NotSuccessStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientManage.SmsFactoryService.HistoryMessageFilter.OrderByOptions OrderBy {
            get {
                return this.OrderByField;
            }
            set {
                if ((this.OrderByField.Equals(value) != true)) {
                    this.OrderByField = value;
                    this.RaisePropertyChanged("OrderBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageReferenceId {
            get {
                return this.PackageReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageReferenceIdField, value) != true)) {
                    this.PackageReferenceIdField = value;
                    this.RaisePropertyChanged("PackageReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageTitle {
            get {
                return this.PackageTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageTitleField, value) != true)) {
                    this.PackageTitleField = value;
                    this.RaisePropertyChanged("PackageTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIdField, value) != true)) {
                    this.ReferenceIdField = value;
                    this.RaisePropertyChanged("ReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((this.StatusIdField.Equals(value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPhone {
            get {
                return this.ToPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPhoneField, value) != true)) {
                    this.ToPhoneField = value;
                    this.RaisePropertyChanged("ToPhone");
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="HistoryMessageFilter.OrderByOptions", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Filters")]
        public enum OrderByOptions : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DateSend = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DateSendDesc = 1,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryMessage", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities.EntitiesDTO")]
    [System.SerializableAttribute()]
    public partial class HistoryMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternativeEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ConfirmationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConfirmationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EntityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EntityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsedCreditField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternativeEmail {
            get {
                return this.AlternativeEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternativeEmailField, value) != true)) {
                    this.AlternativeEmailField = value;
                    this.RaisePropertyChanged("AlternativeEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ConfirmationDate {
            get {
                return this.ConfirmationDateField;
            }
            set {
                if ((this.ConfirmationDateField.Equals(value) != true)) {
                    this.ConfirmationDateField = value;
                    this.RaisePropertyChanged("ConfirmationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ConfirmationStatus {
            get {
                return this.ConfirmationStatusField;
            }
            set {
                if ((this.ConfirmationStatusField.Equals(value) != true)) {
                    this.ConfirmationStatusField = value;
                    this.RaisePropertyChanged("ConfirmationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSend {
            get {
                return this.DateSendField;
            }
            set {
                if ((this.DateSendField.Equals(value) != true)) {
                    this.DateSendField = value;
                    this.RaisePropertyChanged("DateSend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EntityId {
            get {
                return this.EntityIdField;
            }
            set {
                if ((this.EntityIdField.Equals(value) != true)) {
                    this.EntityIdField = value;
                    this.RaisePropertyChanged("EntityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EntityType {
            get {
                return this.EntityTypeField;
            }
            set {
                if ((this.EntityTypeField.Equals(value) != true)) {
                    this.EntityTypeField = value;
                    this.RaisePropertyChanged("EntityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorText {
            get {
                return this.ErrorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTextField, value) != true)) {
                    this.ErrorTextField = value;
                    this.RaisePropertyChanged("ErrorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromName {
            get {
                return this.FromNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromNameField, value) != true)) {
                    this.FromNameField = value;
                    this.RaisePropertyChanged("FromName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromPhone {
            get {
                return this.FromPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.FromPhoneField, value) != true)) {
                    this.FromPhoneField = value;
                    this.RaisePropertyChanged("FromPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDemo {
            get {
                return this.IsDemoField;
            }
            set {
                if ((this.IsDemoField.Equals(value) != true)) {
                    this.IsDemoField = value;
                    this.RaisePropertyChanged("IsDemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText {
            get {
                return this.MessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTextField, value) != true)) {
                    this.MessageTextField = value;
                    this.RaisePropertyChanged("MessageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageReferenceId {
            get {
                return this.PackageReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageReferenceIdField, value) != true)) {
                    this.PackageReferenceIdField = value;
                    this.RaisePropertyChanged("PackageReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageTitle {
            get {
                return this.PackageTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageTitleField, value) != true)) {
                    this.PackageTitleField = value;
                    this.RaisePropertyChanged("PackageTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIdField, value) != true)) {
                    this.ReferenceIdField = value;
                    this.RaisePropertyChanged("ReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((this.StatusIdField.Equals(value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPhone {
            get {
                return this.ToPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPhoneField, value) != true)) {
                    this.ToPhoneField = value;
                    this.RaisePropertyChanged("ToPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsedCredit {
            get {
                return this.UsedCreditField;
            }
            set {
                if ((this.UsedCreditField.Equals(value) != true)) {
                    this.UsedCreditField = value;
                    this.RaisePropertyChanged("UsedCredit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalMessagesPerDay", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities")]
    [System.SerializableAttribute()]
    public partial class TotalMessagesPerDay : ClientManage.SmsFactoryService.TotalMessagesBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerUniqueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSendField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTitle {
            get {
                return this.CustomerTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTitleField, value) != true)) {
                    this.CustomerTitleField = value;
                    this.RaisePropertyChanged("CustomerTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerUniqueId {
            get {
                return this.CustomerUniqueIdField;
            }
            set {
                if ((this.CustomerUniqueIdField.Equals(value) != true)) {
                    this.CustomerUniqueIdField = value;
                    this.RaisePropertyChanged("CustomerUniqueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSend {
            get {
                return this.DateSendField;
            }
            set {
                if ((this.DateSendField.Equals(value) != true)) {
                    this.DateSendField = value;
                    this.RaisePropertyChanged("DateSend");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalMessagesBase", Namespace="http://schemas.datacontract.org/2004/07/SmsFactory.Common.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientManage.SmsFactoryService.TotalMessagesPerDay))]
    public partial class TotalMessagesBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsedCreditField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFail {
            get {
                return this.TotalFailField;
            }
            set {
                if ((this.TotalFailField.Equals(value) != true)) {
                    this.TotalFailField = value;
                    this.RaisePropertyChanged("TotalFail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalMessages {
            get {
                return this.TotalMessagesField;
            }
            set {
                if ((this.TotalMessagesField.Equals(value) != true)) {
                    this.TotalMessagesField = value;
                    this.RaisePropertyChanged("TotalMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalSuccess {
            get {
                return this.TotalSuccessField;
            }
            set {
                if ((this.TotalSuccessField.Equals(value) != true)) {
                    this.TotalSuccessField = value;
                    this.RaisePropertyChanged("TotalSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsedCredit {
            get {
                return this.UsedCreditField;
            }
            set {
                if ((this.UsedCreditField.Equals(value) != true)) {
                    this.UsedCreditField = value;
                    this.RaisePropertyChanged("UsedCredit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsFactoryService.ISmsService")]
    public interface ISmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceContract/IsAlive", ReplyAction="http://tempuri.org/IBaseServiceContract/IsAliveResponse")]
        bool IsAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseServiceContract/WarmUp", ReplyAction="http://tempuri.org/IBaseServiceContract/WarmUpResponse")]
        void WarmUp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/SendPackage", ReplyAction="http://tempuri.org/ISmsService/SendPackageResponse")]
        void SendPackage(ClientManage.SmsFactoryService.SmsPackage package);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/SendMessage", ReplyAction="http://tempuri.org/ISmsService/SendMessageResponse")]
        void SendMessage(ClientManage.SmsFactoryService.CustomerCredentials credentials, ClientManage.SmsFactoryService.SmsMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/SendMessages", ReplyAction="http://tempuri.org/ISmsService/SendMessagesResponse")]
        void SendMessages(ClientManage.SmsFactoryService.CustomerCredentials credentials, System.Collections.Generic.List<ClientManage.SmsFactoryService.SmsMessage> messages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/SendBulkMessage", ReplyAction="http://tempuri.org/ISmsService/SendBulkMessageResponse")]
        void SendBulkMessage(ClientManage.SmsFactoryService.CustomerCredentials credentials, ClientManage.SmsFactoryService.BulkSmsMessage bulkMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/GetCredit", ReplyAction="http://tempuri.org/ISmsService/GetCreditResponse")]
        int GetCredit(ClientManage.SmsFactoryService.CustomerCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/GetHistoryMessages", ReplyAction="http://tempuri.org/ISmsService/GetHistoryMessagesResponse")]
        System.Collections.Generic.List<ClientManage.SmsFactoryService.HistoryMessage> GetHistoryMessages(ClientManage.SmsFactoryService.CustomerCredentials credentials, ClientManage.SmsFactoryService.HistoryMessageFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmsService/GetTotalMessagesPerDay", ReplyAction="http://tempuri.org/ISmsService/GetTotalMessagesPerDayResponse")]
        System.Collections.Generic.List<ClientManage.SmsFactoryService.TotalMessagesPerDay> GetTotalMessagesPerDay(ClientManage.SmsFactoryService.CustomerCredentials credentials, ClientManage.SmsFactoryService.TotalMessagesPerDayFilter filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsServiceChannel : ClientManage.SmsFactoryService.ISmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsServiceClient : System.ServiceModel.ClientBase<ClientManage.SmsFactoryService.ISmsService>, ClientManage.SmsFactoryService.ISmsService {
        
        public SmsServiceClient() {
        }
        
        public SmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsAlive() {
            return base.Channel.IsAlive();
        }
        
        public void WarmUp() {
            base.Channel.WarmUp();
        }
        
        public void SendPackage(ClientManage.SmsFactoryService.SmsPackage package) {
            base.Channel.SendPackage(package);
        }
        
        public void SendMessage(ClientManage.SmsFactoryService.CustomerCredentials credentials, ClientManage.SmsFactoryService.SmsMessage message) {
            base.Channel.SendMessage(credentials, message);
        }
        
        public void SendMessages(ClientManage.SmsFactoryService.CustomerCredentials credentials, System.Collections.Generic.List<ClientManage.SmsFactoryService.SmsMessage> messages) {
            base.Channel.SendMessages(credentials, messages);
        }
        
        public void SendBulkMessage(ClientManage.SmsFactoryService.CustomerCredentials credentials, ClientManage.SmsFactoryService.BulkSmsMessage bulkMessage) {
            base.Channel.SendBulkMessage(credentials, bulkMessage);
        }
        
        public int GetCredit(ClientManage.SmsFactoryService.CustomerCredentials credentials) {
            return base.Channel.GetCredit(credentials);
        }
        
        public System.Collections.Generic.List<ClientManage.SmsFactoryService.HistoryMessage> GetHistoryMessages(ClientManage.SmsFactoryService.CustomerCredentials credentials, ClientManage.SmsFactoryService.HistoryMessageFilter filter) {
            return base.Channel.GetHistoryMessages(credentials, filter);
        }
        
        public System.Collections.Generic.List<ClientManage.SmsFactoryService.TotalMessagesPerDay> GetTotalMessagesPerDay(ClientManage.SmsFactoryService.CustomerCredentials credentials, ClientManage.SmsFactoryService.TotalMessagesPerDayFilter filter) {
            return base.Channel.GetTotalMessagesPerDay(credentials, filter);
        }
    }
}
