//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizCare.SoftHair.UpdateVersion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizCare.SoftHair.UpdateVersion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\SoftHair.
        /// </summary>
        internal static string app_folder {
            get {
                return ResourceManager.GetString("app_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0;Data Source=&quot;{0}&quot;;Persist Security Info=True;Jet OLEDB:Database Password=37614463.
        /// </summary>
        internal static string connection_string {
            get {
                return ResourceManager.GetString("connection_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.dat.
        /// </summary>
        internal static string data_filename {
            get {
                return ResourceManager.GetString("data_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in UpdateVersion.
        /// </summary>
        internal static string FatalErrorTitle {
            get {
                return ResourceManager.GetString("FatalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string files_location {
            get {
                return ResourceManager.GetString("files_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlbumImages,Backup,ClientImages,pl,Upload.
        /// </summary>
        internal static string skip_backup_folders {
            get {
                return ResourceManager.GetString("skip_backup_folders", resourceCulture);
            }
        }
    }
}
